QTD1 = prompt("Qunatas balas Maria comprou? ")
QTD2 = prompt("Quantas balas Maria comprou depois? ")
total = parseInt(QTD1) + parseInt(QTD2)
document.write("Sabendo que Maria comprou ")
document.write(QTD1)
document.write(" balas e depois comprou mais ")
document.write(QTD2)
document.write(", Maria comprou ")
document.write(total)
document.write(" balas no total.")